version: "3"

volumes:
  admin:

services:
  db:
    image: postgres
    command: postgres -c 'max_connections=7000'
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cockroachmsg

  admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "6543:80"
    volumes:
      - admin:/var/lib/pgadmin
    depends_on:
      - db

  app:
    build: .
    restart: always
    command: npm run dev
    ports:
      - "9500:9500"
    volumes:
      - .:/usr/cockroachmsg